version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./src/nginx/my-folder:/usr/share/nginx/html
  apache:
      build: ./src/apache
      ports:
        - "8081:80"
      volumes:
        - ./src/apache:/usr/local/apache2/htdocs