version: '3.8'
services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx/:/usr/share/nginx/html

  apache:
      build: ./src/apache
      ports:
        - "8081:80"
      volumes:
        - ./src/apache:/usr/local/apache2/htdocs

  nodejs:
    build: 
      context: ./src/nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/nodejs:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "tail -f /dev/null"
