version: '3.8'
services:
  nginx:
    build: ./src/nginx
    ports:
      - "8089:80"
    volumes:
      - ./src/nginx:/usr/share/nginx/html
    depends_on:
      - nodejs
      - apache
      - mysql

  apache:
    build: ./src/apache
    ports:
      - "8080:80"
    volumes:
      - ./src/apache:/usr/local/apache2/htdocs
    depends_on:
      - mysql

  nodejs:
    build: ./src/nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./src/nodejs:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./src/mysql:/docker-entrypoint-initdb.d
      - ./src/data/mysql-data:/var/lib/mysql
