project:
  type: website
  output-dir: ../docs

website:
  title: "CMSC408 - Docker Tutorial"
  navbar:
    left:
      - href: background.qmd
        text: Background
      - href: about.qmd
        text: About

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: installing-docker-mac.qmd
        text: Install-Mac
      - href: selecting-base-image.qmd
        text: Selecting-base
      - href: using-docker-compose.qmd
        text: Using Docker-Compose

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
