project:
  type: website
  output-dir: ../docs

website:
  title: "CMSC408 - Docker Tutorial"
  navbar:
    left:
      - href: fundamentals.qmd
        text: Fundamentals
      - href: about.qmd
        text: About

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Installing docker
        contents:
        - href: installing-docker-mac.qmd
          text: Install-Mac
        - href: installing-docker-pc.qmd
          text: Install-PC
      - href: selecting-base-image.qmd
        text: Selecting-base
      - href: using-docker-compose.qmd
        text: Using Docker-Compose

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
