FROM nginx:latest
COPY ./site/index.html /usr/share/nginx/html/
COPY ./site/styles.css /usr/share/nginx/html/
COPY ./site/script.js /usr/share/nginx/html/
COPY ./site/script.js /usr/share/nginx/html/
