FROM nginx:latest

# NGINX looks for the web site root inside
# /usr/share/nginx/html/

# Rather than copying files into this folder,
# We'll map this folder to our local hard disk.

# With this change, we'll be able to change the pages in real-time.

