version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-example-volume
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
